# Docker Compose
# https://docs.docker.com/compose/

version: "3"
services:
  # Python
  app:
    environment: &environment
      - STAGE=local
    image: zsh-docker-aliases-app-dev:0.0.2
    build:
      args:
        stage: dev
        version: 0.0.2

  check:
    image: zsh-docker-aliases-check-dev:0.0.2
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
        version: 0.0.2
    volumes:
      - .:/usr/src
    env_file:
      - .env
